name: peppi
channels:
  - pytorch
  - bioconda
  - dglteam/label/cu118
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - astroid=2.14.2=py38h06a4308_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - boost=1.70.0=py38h9de70de_1
  - boost-cpp=1.70.0=ha2d47e9_1
  - bottleneck=1.3.5=py38h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.12.12=h06a4308_0
  - cairo=1.16.0=h18b612c_1001
  - certifi=2024.2.2=py38h06a4308_0
  - cffi=1.14.6=py38h400218f_0
  - chardet=4.0.0=py38h06a4308_1003
  - conda-package-handling=1.7.3=py38h27cfd23_1
  - contourpy=1.0.5=py38hdb19cb5_0
  - cryptography=3.4.7=py38hd23ed53_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cudatoolkit=11.6.0=hecad31d_10
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - dgl=2.0.0.cu118=py38_0
  - entrypoints=0.4=py38h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=h295c915_0
  - fftw=3.3.9=h27cfd23_1
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - future=0.18.2=py38_1
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - hhsuite=3.3.0=py38pl5321h8ded8fe_5
  - icu=58.2=he6710b0_3
  - idna=2.10=pyhd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.9.1=py38h06a4308_0
  - ipython=8.4.0=py38h06a4308_0
  - isort=5.9.3=pyhd3eb1b0_0
  - jedi=0.18.1=py38h06a4308_1
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - jupyter_client=7.2.2=py38h06a4308_0
  - jupyter_core=4.10.0=py38h06a4308_0
  - kalign2=2.04=hec16e2b_3
  - kiwisolver=1.4.2=py38h295c915_0
  - krb5=1.19.2=hac12032_0
  - lazy-object-proxy=1.6.0=py38h27cfd23_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.107=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20210910=h7f8727e_0
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_1
  - libllvm10=10.0.1=hbcb73fb_5
  - libnpp=11.8.0.86=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.4.0=hecacb30_0
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib-base=3.7.1=py38h417a72b_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py38h06a4308_0
  - munkres=1.1.4=py_0
  - nccl=2.12.12.1=h0800d71_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.5=py38h06a4308_0
  - ninja-base=1.10.2=hd09550d_5
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numexpr=2.8.3=py38h807cd23_0
  - numpy-base=1.24.3=py38h31eccc5_0
  - ocl-icd=2.3.1=h7f98852_0
  - ocl-icd-system=1.0.0=1
  - openmm=7.5.1=py38ha082873_1
  - openssl=1.1.1w=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.3=py38h6a678d5_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pdbfixer=1.7=pyhd3deb0d_0
  - perl=5.32.1=0_h5eee18b_perl5
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py38hace64e9_1
  - pip=22.1.2=py38h06a4308_0
  - pixman=0.38.0=h516909a_1003
  - ply=3.11=py38_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycairo=1.21.0=py38h9c00e7a_1
  - pycodestyle=2.8.0=pyhd3eb1b0_0
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.20=py_2
  - pygments=2.15.1=py38h06a4308_0
  - pylint=2.16.2=py38h06a4308_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.15.7=py38h6a678d5_1
  - pyqt5-sip=12.11.0=py38h6a678d5_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=2.2.0=py3.8_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=py38h06a4308_0
  - pyzmq=23.2.0=py38h6a678d5_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - readline=8.1.2=h7f8727e_1
  - ruamel_yaml=0.15.100=py38h27cfd23_0
  - scikit-learn=1.1.1=py38h6a678d5_0
  - scipy=1.7.1=py38h292c36d_2
  - seaborn=0.11.2=pyhd3eb1b0_0
  - sip=6.6.2=py38h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.2=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.12=py38h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py38h06a4308_0
  - torchtriton=2.2.0=py38
  - tornado=6.1=py38h27cfd23_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.3.0=py38h06a4308_0
  - typing_extensions=4.3.0=py38h06a4308_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py38h5eee18b_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.2=h470a237_5
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==0.13.0
      - aiobotocore==2.3.4
      - aiohttp==3.8.1
      - aiohttp-retry==2.8.3
      - aioitertools==0.10.0
      - aiosignal==1.2.0
      - alembic==1.8.1
      - amqp==5.1.1
      - antlr4-python3-runtime==4.9.3
      - anyio==3.6.1
      - appdirs==1.4.4
      - astor==0.8.1
      - astunparse==1.6.3
      - async-timeout==4.0.2
      - asyncssh==2.12.0
      - atpublic==3.0.1
      - attrs==22.1.0
      - bcrypt==4.0.1
      - billiard==3.6.4.0
      - bio==1.4.0
      - biopython==1.79
      - biothings-client==0.2.6
      - boto3==1.21.21
      - botocore==1.24.21
      - bowler==0.9.0
      - cachetools==5.2.0
      - celery==5.2.7
      - cfgv==3.3.1
      - charset-normalizer==2.1.1
      - click==8.1.3
      - click-didyoumean==0.3.0
      - click-plugins==1.1.1
      - click-repl==0.2.0
      - cloudpickle==2.1.0
      - colabfold==1.3.0
      - colorama==0.4.5
      - colossalai==0.3.0
      - commonmark==0.9.1
      - configobj==5.0.6
      - contextlib2==21.6.0
      - contexttimer==0.3.3
      - dask==2022.1.1
      - databricks-cli==0.17.2
      - deprecated==1.2.13
      - dictdiffer==0.9.0
      - dill==0.3.5.1
      - diskcache==5.4.0
      - distlib==0.3.6
      - distro==1.7.0
      - dm-haiku==0.0.7
      - docker==5.0.3
      - dpath==2.0.6
      - dulwich==0.20.45
      - dvc==2.21.2
      - dvc-data==0.1.23
      - dvc-http==2.19.0
      - dvc-objects==0.1.16
      - dvc-render==0.0.9
      - dvc-s3==2.19.0
      - dvc-task==0.1.2
      - dvclive==0.10.0
      - et-xmlfile==1.1.0
      - fabric==3.0.1
      - fair-esm==1.0.2
      - fastapi==0.80.0
      - fastavro==1.6.0
      - feast==0.23.2
      - filelock==3.12.0
      - fissix==21.11.13
      - flask==2.2.2
      - flatbuffers==2.0.7
      - flatten-dict==0.4.2
      - flufl-lock==7.0
      - frozenlist==1.3.1
      - fsspec==2022.7.1
      - funcy==1.17
      - gast==0.4.0
      - gitdb==4.0.9
      - gitpython==3.1.27
      - google-api-core==2.8.2
      - google-auth==2.11.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - googleapis-common-protos==1.56.4
      - grandalf==0.6
      - greenlet==1.1.2
      - grpcio==1.48.0
      - grpcio-reflection==1.48.0
      - gunicorn==20.1.0
      - gym==0.25.2
      - gym-notices==0.0.8
      - h11==0.13.0
      - h5py==3.7.0
      - hiredis==2.0.0
      - httptools==0.4.0
      - huggingface-hub==0.17.1
      - hydra-core==1.2.0
      - hyperopt==0.1.2
      - identify==2.5.24
      - importlib-metadata==4.12.0
      - importlib-resources==5.9.0
      - iniconfig==1.1.1
      - invoke==2.1.1
      - ipdb==0.13.11
      - itsdangerous==2.1.2
      - jax==0.3.25
      - jaxlib==0.3.25+cuda11.cudnn82
      - jinja2==3.1.2
      - jmespath==1.0.1
      - jmp==0.0.2
      - json-tricks==3.15.5
      - jsonschema==4.14.0
      - keras==2.7.0
      - keras-preprocessing==1.1.2
      - kombu==5.2.4
      - levenshtein==0.20.9
      - libclang==14.0.6
      - llvmlite==0.39.1
      - locket==1.0.0
      - loralib==0.1.1
      - mako==1.2.1
      - markdown==3.4.1
      - markupsafe==2.1.1
      - matplotlib==3.1.3
      - ml2rt==0.2.0
      - mlflow==1.28.0
      - mmh3==3.0.0
      - moreorless==0.4.0
      - msgpack==1.0.5
      - multidict==6.0.2
      - mygene==3.2.2
      - mypy==0.971
      - mypy-extensions==0.4.3
      - nanotime==0.5.2
      - netron==6.1.8
      - networkx==2.8.6
      - ninja==1.11.1
      - nni==2.8
      - nodeenv==1.7.0
      - numba==0.56.2
      - numpy==1.22.4
      - oauthlib==3.2.0
      - omegaconf==2.2.3
      - opencv-python==4.6.0.66
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - pandavro==1.5.2
      - paramiko==3.1.0
      - partd==1.3.0
      - pathspec==0.9.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.5.0
      - pluggy==1.0.0
      - pre-commit==3.3.1
      - prettytable==3.4.0
      - prometheus-client==0.14.1
      - prometheus-flask-exporter==0.20.3
      - proto-plus==1.22.0
      - protobuf==3.19.4
      - psutil==5.9.1
      - py==1.11.0
      - py3dmol==1.8.1
      - pyarrow==8.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pydantic==1.9.2
      - pydot==1.4.2
      - pygit2==1.10.0
      - pygtrie==2.5.0
      - pyjwt==2.4.0
      - pymongo==4.2.0
      - pynacl==1.5.0
      - pyrsistent==0.18.1
      - pytest==7.1.3
      - python-dotenv==0.20.0
      - pythonwebhdfs==0.2.3
      - pywavelets==1.4.1
      - pyyaml==6.0
      - querystring-parser==1.2.4
      - rapidfuzz==2.13.7
      - ray==2.2.0
      - rdkit==2023.3.1
      - redis==3.5.3
      - redisai==1.2.2
      - regex==2022.10.31
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - responses==0.21.0
      - rich==12.5.1
      - rsa==4.9
      - ruamel-yaml==0.17.21
      - ruamel-yaml-clib==0.2.6
      - s3fs==2022.7.1
      - s3transfer==0.5.2
      - safetensors==0.3.1
      - schema==0.7.5
      - scmrepo==0.0.25
      - setuptools==59.8.0
      - shortuuid==1.0.9
      - shtab==1.5.5
      - simplejson==3.17.6
      - smmap==5.0.0
      - sniffio==1.2.0
      - sns==0.1
      - sqlalchemy==1.4.40
      - sqlalchemy2-stubs==0.0.2a25
      - sqlparse==0.4.2
      - starlette==0.19.1
      - tabulate==0.8.10
      - tenacity==8.0.1
      - tensorboard==2.10.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow-cpu==2.7.4
      - tensorflow-estimator==2.7.0
      - tensorflow-io-gcs-filesystem==0.27.0
      - tensorflow-metadata==1.10.0
      - termcolor==2.1.1
      - threadpoolctl==3.1.0
      - tianshou==0.4.9
      - timeout-decorator==0.5.0
      - tokenizers==0.13.2
      - tomlkit==0.11.4
      - toolz==0.12.0
      - tqdm==4.64.0
      - transformers==4.33.1
      - typeguard==2.13.3
      - uvicorn==0.18.2
      - uvloop==0.16.0
      - vine==5.0.0
      - virtualenv==20.23.0
      - volatile==2.1.0
      - voluptuous==0.13.1
      - watchfiles==0.16.1
      - websocket-client==1.3.3
      - websockets==10.3
      - werkzeug==2.2.2
      - xgboost==1.7.3
      - yafp==1.0.0
      - yapf==0.32.0
      - yarl==1.8.1
      - zc-lockfile==2.0
      - zipp==3.8.1
prefix: /home/richard/miniconda3/envs/multiview
