name: multiview
channels:
  - metric-learning
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - boost=1.70.0=py38h9de70de_1
  - boost-cpp=1.70.0=ha2d47e9_1
  - bottleneck=1.3.5=py38h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - cairo=1.16.0=h18b612c_1001
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.14.6=py38h400218f_0
  - chardet=4.0.0=py38h06a4308_1003
  - conda-package-handling=1.7.3=py38h27cfd23_1
  - cryptography=3.4.7=py38hd23ed53_0
  - cudatoolkit=11.6.0=hecad31d_10
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=h295c915_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.11.0=h70c0345_0
  - future=0.18.2=py38_1
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=2.10=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.9.1=py38h06a4308_0
  - ipython=8.4.0=py38h06a4308_0
  - jedi=0.18.1=py38h06a4308_1
  - jinja2=3.1.2=py38h06a4308_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - jupyter_client=7.2.2=py38h06a4308_0
  - jupyter_core=4.10.0=py38h06a4308_0
  - kiwisolver=1.4.2=py38h295c915_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=10.0.1=default_hb85057a_2
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20210910=h7f8727e_0
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.4.0=hecacb30_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.1.1=py38h7f8727e_0
  - matplotlib=3.5.1=py38h06a4308_1
  - matplotlib-base=3.5.1=py38ha18d171_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.5=py38h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - ninja-base=1.10.2=hd09550d_5
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numexpr=2.8.3=py38h807cd23_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1s=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.3=py38h6a678d5_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py38hace64e9_1
  - pip=22.1.2=py38h06a4308_0
  - pixman=0.38.0=h516909a_1003
  - ply=3.11=py38_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycairo=1.21.0=py38h9c00e7a_1
  - pycodestyle=2.8.0=pyhd3eb1b0_0
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.20=py_2
  - pyg=2.1.0=py38_torch_1.12.0_cu116
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.15.7=py38h6a678d5_1
  - pyqt5-sip=12.11.0=py38h6a678d5_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch-cluster=1.6.0=py38_torch_1.12.0_cu116
  - pytorch-metric-learning=1.6.3=pyh39e3cac_0
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.0.9=py38_torch_1.12.0_cu116
  - pytorch-sparse=0.6.15=py38_torch_1.12.0_cu116
  - pytz=2022.1=py38h06a4308_0
  - pyzmq=23.2.0=py38h6a678d5_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - rdkit=2019.09.3=py38hb31dc5d_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.25.1=pyhd3eb1b0_0
  - ruamel_yaml=0.15.100=py38h27cfd23_0
  - scikit-learn=1.1.1=py38h6a678d5_0
  - scipy=1.7.1=py38h292c36d_2
  - seaborn=0.11.2=pyhd3eb1b0_0
  - sip=6.6.2=py38h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.2=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchaudio=0.12.1=py38_cu116
  - tornado=6.1=py38h27cfd23_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.3.0=py38h06a4308_0
  - typing_extensions=4.3.0=py38h06a4308_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.2=h470a237_5
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.32.0=pyhd8ed1ab_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==1.2.0
      - aiobotocore==2.3.4
      - aiohttp==3.8.1
      - aiohttp-retry==2.8.3
      - aioitertools==0.10.0
      - aiosignal==1.2.0
      - alembic==1.8.1
      - amqp==5.1.1
      - antlr4-python3-runtime==4.9.3
      - anyio==3.6.1
      - appdirs==1.4.4
      - astor==0.8.1
      - async-timeout==4.0.2
      - asyncssh==2.12.0
      - atpublic==3.0.1
      - attrs==22.1.0
      - banal==1.0.6
      - billiard==3.6.4.0
      - bio==1.4.0
      - biopython==1.79
      - biothings-client==0.2.6
      - boto3==1.21.21
      - botocore==1.24.21
      - bowler==0.9.0
      - cachetools==5.2.0
      - celery==5.2.7
      - charset-normalizer==2.1.1
      - click==8.1.3
      - click-didyoumean==0.3.0
      - click-plugins==1.1.1
      - click-repl==0.2.0
      - cloudpickle==2.1.0
      - colorama==0.4.5
      - commonmark==0.9.1
      - configobj==5.0.6
      - contextlib2==21.6.0
      - dask==2022.1.1
      - databricks-cli==0.17.2
      - dataset==1.5.2
      - dgl==1.1.3+cu121
      - dictdiffer==0.9.0
      - dill==0.3.5.1
      - diskcache==5.4.0
      - distro==1.7.0
      - docker==5.0.3
      - dpath==2.0.6
      - dulwich==0.20.45
      - dvc==2.21.2
      - dvc-data==0.1.23
      - dvc-http==2.19.0
      - dvc-objects==0.1.16
      - dvc-render==0.0.9
      - dvc-s3==2.19.0
      - dvc-task==0.1.2
      - dvclive==0.10.0
      - fair-esm==1.0.2
      - fastapi==0.80.0
      - fastavro==1.6.0
      - feast==0.23.2
      - filelock==3.8.0
      - fissix==21.11.13
      - flask==2.2.2
      - flatten-dict==0.4.2
      - flufl-lock==7.0
      - fonttools==4.38.0
      - frozenlist==1.3.1
      - fsspec==2022.7.1
      - funcy==1.17
      - gitdb==4.0.9
      - gitpython==3.1.27
      - google-api-core==2.8.2
      - google-auth==2.11.0
      - google-auth-oauthlib==0.4.6
      - googleapis-common-protos==1.56.4
      - grandalf==0.6
      - greenlet==1.1.2
      - grpcio==1.48.0
      - grpcio-reflection==1.48.0
      - gunicorn==20.1.0
      - gym==0.25.2
      - gym-notices==0.0.8
      - h11==0.13.0
      - h5py==3.7.0
      - httptools==0.4.0
      - hydra-core==1.2.0
      - hyperopt==0.1.2
      - importlib-metadata==4.12.0
      - importlib-resources==5.9.0
      - iniconfig==1.1.1
      - itsdangerous==2.1.2
      - jmespath==1.0.1
      - json-tricks==3.15.5
      - jsonschema==4.14.0
      - kombu==5.2.4
      - llvmlite==0.39.1
      - lmdb==1.3.0
      - locket==1.0.0
      - mako==1.2.1
      - markdown==3.4.1
      - mlflow==1.28.0
      - mmh3==3.0.0
      - moreorless==0.4.0
      - mpmath==1.3.0
      - multidict==6.0.2
      - mygene==3.2.2
      - mypy==0.971
      - mypy-extensions==0.4.3
      - nanotime==0.5.2
      - networkx==2.8.6
      - ninja==1.11.1
      - nni==2.8
      - numba==0.56.2
      - numpy==1.22.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.0
      - omegaconf==2.2.3
      - pandavro==1.5.2
      - partd==1.3.0
      - pathspec==0.9.0
      - pkgutil-resolve-name==1.3.10
      - pluggy==1.0.0
      - prettytable==3.4.0
      - prometheus-client==0.14.1
      - prometheus-flask-exporter==0.20.3
      - proto-plus==1.22.0
      - protobuf==3.19.4
      - psutil==5.9.1
      - py==1.11.0
      - pyarrow==8.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pydantic==1.9.2
      - pydot==1.4.2
      - pygit2==1.10.0
      - pygments==2.13.0
      - pygtrie==2.5.0
      - pyjwt==2.4.0
      - pymongo==4.2.0
      - pyrsistent==0.18.1
      - pytest==7.1.3
      - python-dotenv==0.20.0
      - pythonwebhdfs==0.2.3
      - pyyaml==6.0
      - querystring-parser==1.2.4
      - rdkit-pypi==2022.9.2
      - requests-oauthlib==1.3.1
      - responses==0.21.0
      - rich==12.5.1
      - rsa==4.9
      - ruamel-yaml==0.17.21
      - ruamel-yaml-clib==0.2.6
      - s3fs==2022.7.1
      - s3transfer==0.5.2
      - schema==0.7.5
      - scmrepo==0.0.25
      - setuptools==59.8.0
      - shortuuid==1.0.9
      - shtab==1.5.5
      - simplejson==3.17.6
      - smmap==5.0.0
      - sniffio==1.2.0
      - sns==0.1
      - sqlalchemy==1.4.40
      - sqlalchemy2-stubs==0.0.2a25
      - sqlparse==0.4.2
      - starlette==0.19.1
      - sympy==1.12
      - tabulate==0.8.10
      - tenacity==8.0.1
      - tensorboard==2.10.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow-metadata==1.10.0
      - tianshou==0.4.9
      - timeout-decorator==0.5.0
      - tomli==2.0.1
      - tomlkit==0.11.4
      - toolz==0.12.0
      - torch==2.1.2
      - torchdrug==0.2.0
      - torchvision==0.14.0
      - tqdm==4.64.0
      - triton==2.1.0
      - typeguard==2.13.3
      - uvicorn==0.18.2
      - uvloop==0.16.0
      - vine==5.0.0
      - volatile==2.1.0
      - voluptuous==0.13.1
      - watchfiles==0.16.1
      - websocket-client==1.3.3
      - websockets==10.3
      - werkzeug==2.2.2
      - wrapt==1.14.1
      - yarl==1.8.1
      - zc-lockfile==2.0
      - zipp==3.8.1
prefix: /home/richard/miniconda3/envs/multiview
